# Generated by Django 4.0.5 on 2022-06-13 22:15

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usuario_options_alter_usuario_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'usuario', 'verbose_name_plural': 'usuarios'},
        ),
        migrations.AddField(
            model_name='usuario',
            name='imagem',
            field=models.ImageField(default=1, upload_to=users.models.upload_image_user),
            preserve_default=False,
        ),
    ]
