# Generated by Django 4.0.5 on 2022-07-06 22:43

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_usuario_options_usuario_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='administrador',
            new_name='is_staff',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='super_usuario',
            new_name='is_superuser',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='imagem',
            field=models.ImageField(blank=True, upload_to=users.models.upload_image_user),
        ),
    ]
