# Generated by Django 4.0.5 on 2022-07-19 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortener.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('shortened_url', models.CharField(editable=False, max_length=8)),
                ('data_creation', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=shortener.models.time_expiration, editable=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
