# Generated by Django 4.0.5 on 2022-08-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='shortened_url',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.CharField(max_length=600),
        ),
    ]
